import axios from 'axios';

// NVIDIA API configuration
const INVOKE_URL = 'https://integrate.api.nvidia.com/v1/chat/completions';
const API_KEY = process.env.NVIDIA_API_KEY;

// Llama-4-Scout model configuration
const MODEL = 'meta/llama-4-scout-17b-16e-instruct';
const MAX_TOKENS = 512;
const TEMPERATURE = 1.00;
const TOP_P = 1.00;

/**
 * Process web search information using Llama-4-Scout
 * @param {string} researchPlan - The research plan generated by Cerebras AI
 * @param {Array} websites - List of websites to process
 * @returns {Promise<string>} - Processed information from websites
 */
export const processWebSearchInfo = async (researchPlan, websites) => {
  try {
    // Combine research plan with website information for context
    const websiteContent = websites.join('\n');
    const prompt = `Research Plan: ${researchPlan}\n\nWebsites to analyze:\n${websiteContent}\n\nPlease extract and summarize relevant information from these websites based on the research plan.`;

    const payload = {
      model: MODEL,
      messages: [{ role: 'user', content: prompt }],
      max_tokens: MAX_TOKENS,
      temperature: TEMPERATURE,
      top_p: TOP_P,
      frequency_penalty: 0.00,
      presence_penalty: 0.00,
      stream: false
    };

    const headers = {
      'Authorization': `Bearer ${API_KEY}`,
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    };

    const response = await axios.post(INVOKE_URL, payload, { headers });
    
    // Extract the AI's response
    const aiResponse = response.data.choices[0]?.message?.content || 'No relevant information found.';
    
    return aiResponse;
  } catch (error) {
    console.error('Error processing web search info with Llama-4-Scout:', error.message);
    throw new Error('Failed to process web search information');
  }
};
